-- SweetLeads schema — documents the LIVE schema already provisioned in the
-- Supabase project "Sweetleads" (asbadexzjsradvzmzahl). Idempotent.
-- Apply (if recreating from scratch) in the SQL editor:
-- https://supabase.com/dashboard/project/asbadexzjsradvzmzahl/sql/new

do $$ begin
  create type public.fulfillment as enum ('pickup', 'delivery');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.lead_status as enum ('new', 'calling', 'qualified', 'follow_up', 'closed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.transcript_speaker as enum ('agent', 'customer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.campaign_status as enum ('draft', 'active');
exception when duplicate_object then null; end $$;

-- The app keeps a single profile in the row id = 'default'.
create table if not exists public.bakeries (
  id text primary key,
  name text not null,
  location text not null,
  cake_types text[] not null,
  price_min integer not null,
  price_max integer not null,
  fulfillment public.fulfillment[] not null,
  phone text not null,
  hours text not null,
  monthly_budget integer not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id text primary key,
  name text not null,
  phone text not null,
  source text not null,
  status public.lead_status not null,
  call_outcome text,
  next_action text,
  cake_order jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transcript_messages (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.leads (id),
  speaker public.transcript_speaker not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.call_sessions (
  call_sid text primary key,
  lead_id text not null references public.leads (id),
  from_number text not null,
  done boolean not null default false,
  started_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id text primary key,
  bakery_id text not null references public.bakeries (id),
  headline text not null,
  body text not null,
  cta text not null,
  audience text not null,
  daily_budget integer not null,
  status public.campaign_status not null,
  launched_at timestamptz,
  updated_at timestamptz not null default now()
);
