-- Ports bakery-platform/lib/schema.sql (SQLite) into the SweetLeads Postgres
-- database, so the storefront, cart, checkout and order board run on the same
-- project as leads, campaigns and the voice agent.
--
-- Three deliberate differences from the SQLite original:
--
--  1. `bakeries.id` stays TEXT. SweetLeads keeps its single profile in the row
--     id = 'default' (src/lib/server/db.ts), and the original's INTEGER
--     AUTOINCREMENT ids exist only to be foreign keys. Carrying bakery_id as
--     TEXT on every product and order keeps the original's property that
--     multi-bakery is additive.
--  2. `closed_weekdays` is integer[] rather than a JSON string. Postgres has a
--     real array type, so the JSON.parse in getBakery() goes away.
--  3. Money is USD cents rather than NOK øre. The column names already said
--     cents; only the seed values and the formatter change.
--
-- Idempotent, like the rest of supabase/migrations.

/* --------------------------- bakery: shop fields --------------------------- */

-- The fields the storefront needs that the lead-gen profile never had. The
-- SQLite original seeded these and offered no way to edit them; /setup does now.
alter table public.bakeries
  add column if not exists slug              text    not null default 'bakery',
  add column if not exists description       text    not null default '',
  add column if not exists address           text    not null default '',
  add column if not exists email             text    not null default '',
  add column if not exists currency          text    not null default 'USD',
  -- Order after this local hour and the lead time starts counting tomorrow.
  add column if not exists order_cutoff_hour integer not null default 12,
  add column if not exists open_hour         integer not null default 8,
  add column if not exists close_hour        integer not null default 16,
  -- JS getDay(): 0 = Sunday. Matches earliestPickupDate()'s arithmetic.
  add column if not exists closed_weekdays   integer[] not null default '{0}';

create unique index if not exists bakeries_slug_idx on public.bakeries (slug);

/* --------------------------------- catalog -------------------------------- */

create table if not exists public.products (
  id                    bigint generated by default as identity primary key,
  bakery_id             text    not null references public.bakeries (id) on delete cascade,
  name                  text    not null,
  description           text    not null default '',
  category              text    not null default 'Other',
  image_url             text    not null default '',
  base_price_cents      integer not null,           -- price of the default selection
  lead_time_days        integer not null default 1, -- min days notice (0 = same day)
  can_have_cake_text    boolean not null default false,
  cake_text_price_cents integer not null default 0, -- surcharge when cake text is used
  active                boolean not null default true, -- deactivate, never delete
  sort_order            integer not null default 0,
  created_at            timestamptz not null default now()
);

-- One row per selectable value. group_name groups rows into a single-select
-- option group ("Size", "Filling"); exactly one value per group is chosen.
-- Sizes are just another group; the UI shows base + delta as absolute prices.
create table if not exists public.product_options (
  id                bigint generated by default as identity primary key,
  product_id        bigint  not null references public.products (id) on delete cascade,
  group_name        text    not null,
  value_name        text    not null,
  price_delta_cents integer not null default 0,
  is_default        boolean not null default false,
  position          integer not null default 0
);

/* --------------------------------- orders --------------------------------- */

do $$ begin
  create type public.order_status as enum
    ('new', 'confirmed', 'ready', 'picked_up', 'cancelled');
exception when duplicate_object then null; end $$;

create table if not exists public.orders (
  id                bigint generated by default as identity primary key,
  bakery_id         text   not null references public.bakeries (id) on delete cascade,
  order_number      text   not null unique,
  status            public.order_status not null default 'new',
  customer_name     text   not null,
  customer_phone    text   not null,
  customer_email    text   not null,
  pickup_date       date   not null,
  pickup_slot       text   not null,          -- e.g. "10:00-11:00"
  note              text   not null default '',
  total_cents       integer not null,
  payment_provider  text   not null,
  payment_status    text   not null,          -- 'demo_paid' from the mock provider
  payment_reference text   not null,
  -- Mutable state owned by the vendored Daymaker bakery dashboard adapter:
  -- scheduled-date override, uploaded production/delivery photos, and a
  -- "delivered" mark. One JSON blob so the core order model stays untouched.
  assignment_state  jsonb  not null default '{}'::jsonb,
  -- Set when the order was created from a qualified phone lead rather than the
  -- web cart, which is the seam between SweetLeads and the storefront.
  lead_id           text   references public.leads (id) on delete set null,
  created_at        timestamptz not null default now()
);

-- Frozen snapshot of what was ordered: names, prices and chosen options are
-- copied at order time so later catalog edits never rewrite history.
create table if not exists public.order_lines (
  id               bigint generated by default as identity primary key,
  order_id         bigint  not null references public.orders (id) on delete cascade,
  product_id       bigint  not null,
  product_name     text    not null,
  qty              integer not null,
  unit_price_cents integer not null,
  line_total_cents integer not null,
  options_json     jsonb   not null default '[]'::jsonb, -- [{id, group, value, priceDeltaCents}]
  cake_text        text    not null default ''
);

/* -------------------------------- indexes --------------------------------- */

create index if not exists products_bakery_idx
  on public.products (bakery_id, active, sort_order);
create index if not exists product_options_product_idx
  on public.product_options (product_id, group_name, position);
create index if not exists orders_bakery_idx
  on public.orders (bakery_id, status, pickup_date);
create index if not exists order_lines_order_idx
  on public.order_lines (order_id);
create index if not exists orders_lead_idx
  on public.orders (lead_id);

/* ---------------------------------- RLS ----------------------------------- */

-- Same posture as the existing tables: every read and write goes through the
-- service-role client in src/lib/supabase/admin.ts, so RLS is on with no
-- policies at all. service_role bypasses it; anon/authenticated get nothing.
-- This is also what closes the original's open admin API: there is no
-- browser-reachable path to these tables that does not pass through a Route
-- Handler.
alter table public.products        enable row level security;
alter table public.product_options enable row level security;
alter table public.orders          enable row level security;
alter table public.order_lines     enable row level security;
