-- The cake archive, and the proposals built from it.
--
-- Why this exists, from two customer calls:
--
--   Even Dough (12 staff, one full-time person on email/phone) has ~2,000
--   photos of past cakes in folders. Her ask, verbatim: "she said rainbow,
--   boom, send her seven rainbow cakes we made." She measured the payoff
--   herself — when a customer attaches a gallery picture the thread runs
--   "two emails, three emails and you're done" instead of seven to twelve.
--
--   Sweet Lady Jane (400 custom cakes a week, $300-$1000+ each) described the
--   same thing from the other side: "if they want a quick answer, and we
--   won't be able to answer before 24 hours, at least the AI can produce a
--   bunch of ideas... in the meantime that person can be entertained by
--   looking at different pictures."
--
-- Both are describing retrieval over past work, not a better intake form.
--
-- The second reason this table exists is pricing. Sweet Lady Jane's stated
-- objection to AI quoting was labour estimation: "the actual judgment call of
-- how much something will cost in terms of hours and money, that's where they
-- fail." Correct — so the agent never judges. `price_cents` and `labor_hours`
-- on past cakes turn a quote into a comparables lookup, the way an appraiser
-- prices a house: find the closest things you have actually made, and read
-- off what they took. Sparse or scattered comps produce low confidence, which
-- routes to a human — which is already how Sweet Lady Jane runs it, roughly
-- 70% quoted by the custom-cake person and 30% confirmed by the kitchen.

/* ------------------------------- the archive ------------------------------ */

create table if not exists public.archive_cakes (
  id             bigint generated by default as identity primary key,
  bakery_id      text not null references public.bakeries (id) on delete cascade,

  -- 'archive' is a real past cake; 'seed' is demo data. Kept explicit so a
  -- quote can never be built from invented history without it being visible.
  source         text not null default 'archive',

  photo_url      text not null default '',
  thumbnail_url  text not null default '',

  title          text not null,
  -- Read aloud when the caller cannot look at their phone. Written to be
  -- spoken, not skimmed.
  spoken_description text not null default '',

  -- Retrieval keys. Deliberately structured rather than free text: the
  -- customer's own examples ("rainbow", "bear") are tag lookups, not
  -- semantic search, and tags stay debuggable when a match looks wrong.
  occasion       text[] not null default '{}',
  themes         text[] not null default '{}',
  colors         text[] not null default '{}',
  techniques     text[] not null default '{}',
  tiers          integer not null default 1,
  servings       integer,

  -- Outcome data. Null is normal and honest: a cake with no recorded price
  -- can still be shown as a design, it just cannot vote on a quote.
  price_cents    integer,
  labor_hours    numeric(4,1),
  made_on        date,

  -- Upgrade path: a caption embedding once an embeddings endpoint is wired.
  -- jsonb rather than vector so the archive works before pgvector is enabled;
  -- scoring already treats this as optional (see src/lib/archive/retrieval.ts).
  embedding      jsonb,

  active         boolean not null default true,
  created_at     timestamptz not null default now()
);

create index if not exists archive_cakes_bakery_idx
  on public.archive_cakes (bakery_id, active);
create index if not exists archive_cakes_themes_idx
  on public.archive_cakes using gin (themes);
create index if not exists archive_cakes_occasion_idx
  on public.archive_cakes using gin (occasion);
create index if not exists archive_cakes_price_idx
  on public.archive_cakes (bakery_id, price_cents);

/* ------------------------------- proposals -------------------------------- */

-- A set of past cakes shown to one caller. On a phone call the options are
-- numbered and texted as a link, so the caller can answer "number three"
-- out loud without the agent needing to see their screen.
create table if not exists public.proposals (
  id           bigint generated by default as identity primary key,
  -- Short, unambiguous in a URL sent by SMS.
  code         text not null unique,
  bakery_id    text not null references public.bakeries (id) on delete cascade,
  lead_id      text references public.leads (id) on delete cascade,

  -- What the agent understood the caller to want. Kept so a human reviewing
  -- the quote can see the brief the options were chosen against.
  brief        jsonb not null default '{}'::jsonb,

  -- Comps-based estimate for the chosen option, with its confidence.
  estimate     jsonb,

  created_at   timestamptz not null default now(),
  opened_at    timestamptz,
  chosen_position integer
);

create index if not exists proposals_lead_idx on public.proposals (lead_id);

create table if not exists public.proposal_options (
  id               bigint generated by default as identity primary key,
  proposal_id      bigint not null references public.proposals (id) on delete cascade,
  -- The number the caller says out loud. 1-based.
  position         integer not null,
  archive_cake_id  bigint not null references public.archive_cakes (id) on delete cascade,
  -- A band, not a point. A custom cake is not a catalogue item and quoting it
  -- to the dollar on a first call is how bakeries lose money.
  price_low_cents  integer not null,
  price_high_cents integer not null,
  -- Why this one was shown. For the human approving the quote, and for
  -- debugging retrieval when a match looks odd.
  rationale        text not null default '',
  -- True for the deliberate one-step-up option. Sweet Lady Jane: show what is
  -- possible at the next budget so the caller can calibrate before a person
  -- ever speaks to them.
  above_budget     boolean not null default false,

  unique (proposal_id, position)
);

create index if not exists proposal_options_proposal_idx
  on public.proposal_options (proposal_id, position);

/* ---------------------------------- RLS ----------------------------------- */

-- Same posture as every other table here: all access goes through the
-- service-role client in src/lib/supabase/admin.ts, so RLS is on with no
-- policies. service_role bypasses it; anon and authenticated get nothing.
-- The public proposal page reads through a Route Handler, not the browser.
alter table public.archive_cakes    enable row level security;
alter table public.proposals        enable row level security;
alter table public.proposal_options enable row level security;
